Repository wibudev/NES-Emulator-Collection, pull requests merged in 2022-10, with the labels that each got.

#1 Fire emblem 4 RE
  fe4_regeneration.jad
Labels: hacktoberfest-accepted

#2 Add Zuma Revenge.jar
  Zumas_Revenge_240.jar
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 Add Wonder Zoo Nokia.jar
  Wonder_Zoo_240_5e4a323_nok.jar
Labels: enhancement, hacktoberfest-accepted

#4 Update Readme.md
  README.md
Labels: documentation, hacktoberfest-accepted

#6 Tekken Mobile Jar
  Tekken_Mobile_240_nok.jar
Labels: enhancement

#7 Add Sonic jar
  SonicRunnersAdventure_240_nok.jar
Labels: enhancement

#9 Add Cowboys vs Alien Jar
  Cowboys_Aliens_240_nok.jar
Labels: documentation, good first issue

#11 Add Snaxe Deluxe
  Snake_Deluxe_2_240.jar
Labels: enhancement

#12 Add Snowboarding 3D
  Extreme_Air_Snowboarding_3D.jar
Labels: enhancement
