Repository wibudev/NES-Emulator-Collection, pull requests merged in 2023-09, with the labels that each got.

#25 Add Pes 2009 Nokia .jar
  PES_2009_240x320_nok.jar
Labels: enhancement, good first issue, hacktoberfest-accepted

#26 Add PES 2008 Nokia .jar
  PES_2008_240_nok.jar
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#27 Add Dungeon Hunter .jar
  Dungeon_Hunter_3_240_5e4a323_nok.jar
Labels: enhancement, hacktoberfest-accepted

#28 Add Cyber Lords Arcology .jar
  Cyberlords_Arcology_240_nok.jar
  Lost_Empire_240.jar
Labels: documentation, good first issue, hacktoberfest-accepted

#29 Add Final Fantasy Mobile .jar
  Final_Fantasy_240_nok.jar
Labels: documentation, enhancement, hacktoberfest-accepted
